ibw_blog_homepage:
    path:     /hello/{name}
    defaults: { _controller: IbwBlogBundle:Default:index }


ibw_blog_page:
    type: rest
    prefix: /v1
    resource:  "Ibw\BlogBundle\Controller\\PageController"
    name_prefix: api_1_ #naming collision