<?php

namespace Ibw\JobeetBundle\Entity;

/**
 * IbwJobeetBundleRepositoryJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IbwJobeetBundleRepositoryJobRepository extends \Doctrine\ORM\EntityRepository
{
}
